server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: suibe-math
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/suibe_mma?serverTimezone=Asia/Shanghai
    username: root
    password: chrt
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 20
      min-idle: 3
  session:
    timeout: 86400

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html