mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mappers/*
  type-aliases-package: com.suibe.suibe_mma.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl