server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: suibe-math
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/suibe_mma?serverTimezone=Asia/Shanghai
    username: root
    password: chrt
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 20
      min-idle: 3
  session:
    timeout: 86400

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 5000ms